跨图寻路("钱庄", 65, 40)
延时(3000)
对话NPC("孙进宝")
延时(1500)
NPC二级对话("将元宝兑换成元宝票")
延时(2000)
LUA_Call([[setmetatable(_G, {__index = YuanbaopiaoExchange_Env});YuanbaoPiaoExchange_Max_Clicked();]])
延时(1000)
LUA_Call([[setmetatable(_G, {__index = YuanbaopiaoExchange_Env});YuanbaopiaoExchange_OK_Clicked();]])
延时(1000)
LUA_Call([[setmetatable(_G, {__index = YuanbaopiaoExchange_Env});YuanbaopiaoExchange_Close();]])