LUA_Call([[setmetatable(_G, {__index = PlayerQuicklyEnter_Env});PlayerQuicklyEnter_Clicked(19)]])
延时(2000)

LUA_Call([[setmetatable(_G, {__index = NationalDay_Guide_Env});NationalDay_Guide_Clicked(7)]])
延时(2000)

-- 根据需要修改, 铜花池15个，银花池10个，金花池5个，每个池子中物品编号为：1~30
-- 铜花池
LUA_Call([[setmetatable(_G, {__index = OctoberBag_Env});OctoberBag_ShowFrame(1)]])
延时(1000)
LUA_Call([[setmetatable(_G, {__index = OctoberBag_Env});OctoberBag_ShowItem_Clicked(6);]])
延时(1000)
LUA_Call([[setmetatable(_G, {__index = OctoberBag_Env});OctoberBag_ShowItem_Clicked(7);]])
延时(1000)
LUA_Call([[setmetatable(_G, {__index = OctoberBag_Env});OctoberBag_ShowItem_Clicked(8);]])
延时(1000)
LUA_Call([[setmetatable(_G, {__index = OctoberBag_Env});OctoberBag_ShowItem_Clicked(9);]])
延时(1000)
LUA_Call([[setmetatable(_G, {__index = OctoberBag_Env});OctoberBag_ShowItem_Clicked(10);]])
延时(1000)
LUA_Call([[setmetatable(_G, {__index = OctoberBag_Env});OctoberBag_ShowItem_Clicked(16);]])
延时(1000)
LUA_Call([[setmetatable(_G, {__index = OctoberBag_Env});OctoberBag_ShowItem_Clicked(17);]])
延时(1000)
LUA_Call([[setmetatable(_G, {__index = OctoberBag_Env});OctoberBag_ShowItem_Clicked(18);]])
延时(1000)
LUA_Call([[setmetatable(_G, {__index = OctoberBag_Env});OctoberBag_ShowItem_Clicked(19);]])
延时(1000)
LUA_Call([[setmetatable(_G, {__index = OctoberBag_Env});OctoberBag_ShowItem_Clicked(20);]])
延时(1000)
LUA_Call([[setmetatable(_G, {__index = OctoberBag_Env});OctoberBag_ShowItem_Clicked(26);]])
延时(1000)
LUA_Call([[setmetatable(_G, {__index = OctoberBag_Env});OctoberBag_ShowItem_Clicked(27);]])
延时(1000)
LUA_Call([[setmetatable(_G, {__index = OctoberBag_Env});OctoberBag_ShowItem_Clicked(28);]])
延时(1000)
LUA_Call([[setmetatable(_G, {__index = OctoberBag_Env});OctoberBag_ShowItem_Clicked(29);]])
延时(1000)
LUA_Call([[setmetatable(_G, {__index = OctoberBag_Env});OctoberBag_ShowItem_Clicked(30);]])
延时(1000)

LUA_Call([[setmetatable(_G, {__index = OctoberBag_Env});OctoberBag_Button1_Clicked();]])
延时(2000)
LUA_Call([[setmetatable(_G, {__index = WuhunQuest_Env});WuhunQuest_Bn1Click();]])


-- 银花池
延时(2000)
LUA_Call([[setmetatable(_G, {__index = OctoberBag_Env});OctoberBag_ShowFrame(2)]])
延时(2000)
LUA_Call([[setmetatable(_G, {__index = OctoberBag_Env});OctoberBag_ShowItem_Clicked(6);]])
延时(1000)
LUA_Call([[setmetatable(_G, {__index = OctoberBag_Env});OctoberBag_ShowItem_Clicked(7);]])
延时(1000)
LUA_Call([[setmetatable(_G, {__index = OctoberBag_Env});OctoberBag_ShowItem_Clicked(8);]])
延时(1000)
LUA_Call([[setmetatable(_G, {__index = OctoberBag_Env});OctoberBag_ShowItem_Clicked(9);]])
延时(1000)
LUA_Call([[setmetatable(_G, {__index = OctoberBag_Env});OctoberBag_ShowItem_Clicked(10);]])
延时(1000)
LUA_Call([[setmetatable(_G, {__index = OctoberBag_Env});OctoberBag_ShowItem_Clicked(11);]])
延时(1000)
LUA_Call([[setmetatable(_G, {__index = OctoberBag_Env});OctoberBag_ShowItem_Clicked(12);]])
延时(1000)
LUA_Call([[setmetatable(_G, {__index = OctoberBag_Env});OctoberBag_ShowItem_Clicked(13);]])
延时(1000)
LUA_Call([[setmetatable(_G, {__index = OctoberBag_Env});OctoberBag_ShowItem_Clicked(14);]])
延时(1000)
LUA_Call([[setmetatable(_G, {__index = OctoberBag_Env});OctoberBag_ShowItem_Clicked(15);]])
延时(1000)

LUA_Call([[setmetatable(_G, {__index = OctoberBag_Env});OctoberBag_Button1_Clicked(); ]])
延时(2000)
LUA_Call([[setmetatable(_G, {__index = WuhunQuest_Env});WuhunQuest_Bn1Click();]])


-- 金花池
延时(2000)
LUA_Call([[setmetatable(_G, {__index = OctoberBag_Env});OctoberBag_ShowFrame(3)]])
延时(2000)
LUA_Call([[setmetatable(_G, {__index = OctoberBag_Env});OctoberBag_ShowItem_Clicked(1);]])
延时(1000)
LUA_Call([[setmetatable(_G, {__index = OctoberBag_Env});OctoberBag_ShowItem_Clicked(2);]])
延时(1000)
LUA_Call([[setmetatable(_G, {__index = OctoberBag_Env});OctoberBag_ShowItem_Clicked(3);]])
延时(1000)
LUA_Call([[setmetatable(_G, {__index = OctoberBag_Env});OctoberBag_ShowItem_Clicked(4);]])
延时(1000)
LUA_Call([[setmetatable(_G, {__index = OctoberBag_Env});OctoberBag_ShowItem_Clicked(5);]])
延时(1000)

LUA_Call([[setmetatable(_G, {__index = OctoberBag_Env});OctoberBag_Button1_Clicked(); ]])
延时(2000)
LUA_Call([[setmetatable(_G, {__index = WuhunQuest_Env});WuhunQuest_Bn1Click();]])

延时(2000)
LUA_Call([[setmetatable(_G, {__index = OctoberBag_Env});OctoberBag_Close_Clicked()]])